### ISSUE TITLE
Ubuntu 18.04 with Java 10.0.1 error when running marytts

### ISSUE THREAD

**Issue by shifters67** [marytts/marytts-installer#15] opened 2018-08-07 16:08 UTC
Hi,

when trying to run marytts (to do anything) you get the error

Could not determine java version from '10.0.1'.

every time and it aborts.  Any ideas?

regards

Tom

**Comment by psibre** [comment] 2018-08-07 16:29
Are you sure? Works for me:
```
$ sdk use java 10.0.1-zulu 

Using java version 10.0.1-zulu in this shell.
raz:marytts-installer ingmar$ ./marytts 
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :verify 
Verify  voice-cmu-slt-hsmm-5.2.jar

> Task :install 
Copy    voice-cmu-slt-hsmm-5.2.jar
Copy    marytts-lang-en-5.2.jar
Copy    marytts-runtime-5.2.jar
Copy    marytts-signalproc-5.2.jar
Copy    marytts-common-5.2.jar
Copy    commons-lang-2.6.jar
Copy    commons-io-2.5.jar
Copy    jtok-core-1.9.3.jar
Copy    slf4j-log4j12-1.6.1.jar
Copy    log4j-1.2.16.jar
Copy    fast-md5-2.7.1.jar
Copy    groovy-all-2.4.5.jar
Copy    icu4j-54.1.1.jar
Copy    commons-collections-3.2.2.jar
Copy    emotionml-checker-java-1.1.jar
Copy    guava-14.0.1.jar
Copy    trove4j-2.0.2.jar
Copy    httpcore-nio-4.1.jar
Copy    httpcore-4.1.jar
Copy    opennlp-tools-1.5.3.jar
Copy    opennlp-maxent-3.0.3.jar
Copy    hsqldb-2.0.0.jar
Copy    Jampack-1.0.jar
Copy    jama-1.0.3.jar
Copy    swing-layout-1.0.3.jar
Copy    slf4j-api-1.6.1.jar
Copy    jwnl-1.3.3.jar

> Task :server 
MARY server 5.2 starting as a HTTP server... started in 2.888 s on port 59125
```

**Comment by shifters67** [comment] 2018-08-07 17:33
Thanks for the response - interesting tool SDK which i did not know about.

Installed it - was using 10.0.1 but not the zulu version.  Installed it  and the same result!

I uninstalled openjdk and installed the oracle 8 version and it all works fine!

Many thanks for this handy tool so i can install and experiment with it!

Tom

**Comment by psibre** [comment] 2018-08-07 17:46
Could you please paste your exact command and the output you're getting, including the error message?

**Comment by psibre** [comment] 2018-08-08 02:08
Thanks for the update. I'm just trying to narrow down what's causing the problem, triggered by Java 10. But we're planning more development on this installer soon anyway, including a Gradle update, so hopefully this issue won't persist.
I'm closing this for now, but please reopen it and report further details if you manage to reproduce it.

**Closed by psibre** 2018-08-08 02:08 UTC

**Comment by ThaDaVos** [comment] 2021-12-08 20:07
Having the same issue but then Java 11....

![image](https://user-images.githubusercontent.com/5251028/145276808-cd4b54b1-db80-4c0d-86d1-8fa443f85b10.png)

After running `./marytts install:cmu-slt`

If I clone marytts itself, I can run it just fine - but it's so hard to get voices
